### ISSUE TITLE
possible to add humidity and temperature sensor?

### ISSUE THREAD

**Issue by harryberlin** [lorenzspenger/comfospot-50#4]
Hello

very cool project.
Do you think it's easy to add an humidity and temperture sensor to get an automatic regulation implemented?
I never did program yaml, only python and C.
Is it possible to port to C?

would be nice to get an answer.

**Comment by thatslolo** [comment]
Hi,

the esp has at least three unused GPIO. So it shouldn't be an issue to add an i2c T/H sensor such as AHT20 or SHT3 to the board. Even as a prototype since every port is broken out.
Software wise it would be easy to add in ESPHome, but I'm not sure which kind of automation you would suggest.

Concerning the port to C/(Micro-)Python:
ESPHome is used for easy integratio in Home Assistant. Most of the logic interacting with the Comfospot is implemented in lambda calls (inline C-like functions).

I do think I have some more docu of the reverse engineering I could provide if interested.

**Comment by harryberlin** [comment]
Thanks for reply.

I did order the PCBs few days ago. 
next order is about AHT20, ESP32-C3 and the connectors.

if you like you can send to avr-ibus@gmx.net

**Comment by harryberlin** [comment]
So, i have received the pcbs and ESP32C3 WeAct Studio devices.
I don't know how the get upload your program.
Did setup home assitant on virtual box for the moment.
Could you guide me, how to get it working?

**Comment by thatslolo** [comment]
basically you add the esphome addon and add the config via a package to a new device. https://esphome.io/guides/getting_started_hassio

[Software/lftung_xxx.yaml](https://github.com/thatslolo/comfospot-50/blob/592dd7704b8d5a9dc0bce380b7015109c28eae16/Software/lftung_xxx.yaml) is a working example.

**Comment by harryberlin** [comment]
so, took a while to solder the pcb and upload firmware.
needed to compile at separted system, the raspberry 2 freezed after some time during compiling.
the connector on top is an other one, but it's working.
![image](https://github.com/user-attachments/assets/71e4f323-a0fb-46af-971f-5874dd168ebc)


finally, i don't have the functions on dash.
do i need some further steps?
the overview in esphome is this
![image](https://github.com/user-attachments/assets/96d8fced-83b5-48c8-808e-710653be7d00)

**Comment by lorenzspenger** [comment]
Basically Home Assistant should discover the device on the network and you can add it to your dashboard from there. Seems like you didn't create your own config for the device which I would recommend. Also you can simply flash it from [here](https://lorenzspenger.github.io/Comfospot-50-installer/) and adopt it afterwards into your own ESPHome Dashbaord

**Comment by harryberlin** [comment]
Got it working, after swap to raspberry 4 with official homeassistant image.
Thank you for your help.

in my case: yaml is such an annoying scripting language. i don't know, if i will understand this, to add some other features.
